version: '3.8'
services:
  dashboard-sonar-app:
    container_name: dashboard_sonar_app
    restart: always
    env_file: .env
    build: .
    networks:
      - db_network
      - web_network
  nginx:
    container_name: nginx
    restart: always
    image: "nginx:latest"
    ports:
      - "5085:5085"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - web_network
    depends_on: 
      - dashboard-sonar-app
  flask_db:
    container_name: flask_db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: demo_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

  
networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge
 