version: "3.3"
services:
  db_db:
    container_name: db_db
    restart: always
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - db_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./bbdd/init.sql:/docker-entrypoint-initdb.d/create_tables.sql

  dashboard-sonar-app:
    container_name: dashboard_sonar_app
    restart: always
    env_file: .env
    build: .
    networks:
      - db_network
      - web_network    
    depends_on:
      - db_db
    

  nginx:
    container_name: nginx
    restart: always
    image: "nginx:latest"
    ports:
      - "5085:5085"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - web_network
    depends_on:
      - dashboard-sonar-app

networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
