name: CD Pipeline to Google Cloud Run (staging and production)
on:
  push:
    branches:
      - develop
  workflow_dispatch: {}
  release:
    types: published

env:
  PORT: 5001
  IMAGE_NAME: ${{ github.repository }}

jobs:
    push_to_registry:
        runs-on: ubuntu-22.04
        name: Push Docker image to Docker Hub
        steps:
        - name: Check out the repo
          uses: actions/checkout@v4

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2

        - name: Log in to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Extract metadata (tags, labels) for Docker
          id: meta
          uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
          with:
            images: ${{ env.IMAGE_NAME }}

        - name: Build and push Docker image
          uses: docker/build-push-action@v2
          with:
            context: "{{defaultContext}}"
            push: true
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}
